---
title: 'Appendix1: Study Area and Data Collection'
bibliography: Reference.bib
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Study Area and Data Collection
## Study Area
The study area for this chapter covers most parts of the Jung and Jongno districts (16.6km<sup>2</sup>) which is the CBD of Seoul. This CBD zone is also referred to as the “Sadaemoon” area, known as the four gates named by the previous monarchy. There are eight sub-districts^[Sajik, Cheongwoonhyoja, Samcheong, Gahoe, Jongno 1-4ga, Jongno 5-6ga, Ewha, and Hyewha] in the Jongno district and seven sub-districts^[Sogong, Hoehyeon, Myung, Pil, Jangchoong, Gwanghee, and Euljiro] in Jung. This area plays a central role in business, tourism, shopping, and transit to sub-civic centres.

To improve urban air quality, Seoul planned a Green Transport Scheme which set a clean air zone within the four gates of central Seoul. Unlike London’s ULEZ (Ultra Low Emission Zone), the government has fined vehicles that do not meet the emission standards since December 2019. Despite the attempt to provide better air quality for citizens and commuters, there are still concerns about whether the reduced traffic has benefited air quality since the commencement of peak hours, or has caused another problem for those drivers whose vehicles do not meet the standard who coercively have to change their mode of transport.

Seoul CBD was chosen because first, approximately 300,000 people and 1.3 million vehicles commute to the area every day, second, direct and indirect effects from the exhaust and non-exhaust emissions release notorious levels of particulates which can affect residents' and commuters' health, and lastly, hardly any scientific studies have discovered the association between vehicle ban and air quality after the 'Green Transport Scheme' was initiated. More TRAP studies, such as London Low Emission Zone (LEZ) are needed [@Kelly2011a; @Beevers2013a; @Beevers2016; @Halonen2016d].




# References {-}